export const CHANNELS = [
  { id: 'welcome',  label: 'welcome'  },
  { id: 'about-me', label: 'about-me' },
  { id: 'skills',   label: 'skills'   },
  { id: 'projects', label: 'projects' },
  { id: 'contact',  label: 'contact'  },
]

export const PROJECTS = [
  {
    title: '신한카드 운영',
    category: 'Web Publishing',
    period: '2022.04 ~ 2024.12',
    desc: '신한카드 웹 유지보수 운영 및 신규 서비스 퍼블리싱',
    tags: ['HTML', 'CSS', 'JavaScript', 'jQuery', 'Figma', 'Swiper'],
    color: '#0046ff',
    image: '/shinhancard.png',
    linkType: 'url',
    link: 'https://www.shinhancard.com',
  },
  {
    title: '카드신청 비대면 신분증 인증',
    category: 'UI/UX Publishing',
    period: '2024.05 ~ 2024.11',
    desc: '비대면 신분증 인증 시스템 UI/UX 퍼블리싱',
    tags: ['HTML', 'CSS', 'JavaScript', 'jQuery', 'Figma'],
    color: '#eb459e',
    image: '/OCR.png',
    linkType: 'mobile',
    link: '/OCR/main.html',
  },
  {
    title: 'M4A 사내 홈페이지 리뉴얼',
    category: 'Web Publishing',
    period: '2025.01 ~ 2025.04',
    desc: 'M4A 사내 홈페이지 전면 리뉴얼 퍼블리싱',
    tags: ['HTML', 'CSS', 'JavaScript', 'Figma'],
    color: '#57f287',
    image: '/m4a.png',
    linkType: 'url',
    link: 'https://m4a.co.kr/html/Works.html',
  },
  {
    title: 'NH Pay 다국어 고도화',
    category: 'Vue.js Publishing',
    period: '2025.03 ~ 2025.11',
    desc: 'NH Pay 글로벌 서비스 다국어 퍼블리싱',
    tags: ['다국어', 'Vue.js', 'SCSS'],
    color: '#fee75c',
    image: '/nhcard.png',
    linkType: 'url',
    link: 'https://card.nonghyup.com',
  },
  {
    title: '하나은행 서비스 고도화',
    category: 'React',
    period: '2025.05 ~ 현재',
    desc: '하나은행 웹 서비스 고도화 퍼블리싱',
    tags: ['React', 'SCSS', 'Figma'],
    color: '#00927B',
    image: '',
    linkType: 'url',
    link: 'https://www.hanabank.com',
  },
]
